<?php
/**
 * Created by PhpStorm.
 * User: rookie
 * Url : PTP6.Com
 * Date: 2017/6/28
 * Time: 16:40
 */
namespace App;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    const SEX_UN = 10;
    const SEX_BOY = 20;
    const SEX_GIRL = 30;

    //绑定表
    protected $table = 'student';

    //开启添加时间以及更新时间自动维护
    public $timestamps = true;

    //开启批量添加字段
    protected $fillable = ['name','age','sex'];

    //设置维护时间格式为时间戳
    protected function getDateFormat()
    {
        return time(); // TODO: Change the autogenerated stub
    }
    //设置输出时间格式为原样
    protected function asDateTime($value)
    {
        return $value; // TODO: Change the autogenerated stub
    }


    public function sex ($id = null)
    {
        $arr = array(
          self::SEX_UN => '未知',
            self::SEX_BOY => '男',
            self::SEX_GIRL => '女',
        );

        if ($id !== null) {
            return array_key_exists($id,$arr) ? $arr[$id] : $arr[self::SEX_UN];
        }
        return $arr;

    }

}